-- Attendance sync mirror tables for importing Industryprime_Attendance into FMS.
-- Run this in the FMS to APPLICATION Supabase SQL editor before enabling the cron.

create table if not exists public.attendance_sync_records (
  id bigint generated by default as identity primary key,
  source_project text not null,
  source_table text not null,
  source_record_key text not null,
  payload jsonb not null,
  source_updated_at timestamptz null,
  first_synced_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now()
);

create unique index if not exists attendance_sync_records_source_unique
  on public.attendance_sync_records (source_project, source_table, source_record_key);

create index if not exists attendance_sync_records_table_idx
  on public.attendance_sync_records (source_table);

create index if not exists attendance_sync_records_payload_gin_idx
  on public.attendance_sync_records using gin (payload);

create index if not exists attendance_sync_records_source_table_lower_idx
  on public.attendance_sync_records (lower(source_table));

create table if not exists public.attendance_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  status text not null default 'running',
  trigger_source text not null default 'manual',
  source_project text null,
  tables text[] not null default '{}',
  rows_read integer not null default 0,
  rows_upserted integer not null default 0,
  error text null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists attendance_sync_runs_started_idx
  on public.attendance_sync_runs (started_at desc);

-- Recreate views because PostgreSQL cannot rename/reorder existing view columns
-- with CREATE OR REPLACE VIEW.
drop view if exists public.attendance_sync_leave;
drop view if exists public.attendance_sync_attendance;

create view public.attendance_sync_attendance
with (security_invoker = true) as
select
  id as sync_id,
  source_project,
  source_table,
  source_record_key,
  payload->>'id' as attendance_id,
  payload->>'employee_id' as employee_id,
  coalesce(
    payload->>'employee_name',
    payload->>'full_name',
    payload->>'name',
    payload->>'display_name',
    payload->'employee'->>'name',
    payload->'employee'->>'full_name',
    concat_ws(' ', payload->'employee'->>'first_name', payload->'employee'->>'last_name')
  ) as employee_name,
  nullif(coalesce(
    payload->>'date',
    payload->>'attendance_date',
    payload->>'attendanceDate',
    payload->>'work_date',
    payload->>'punch_date',
    left(payload->>'created_at', 10)
  ), '')::date as attendance_date,
  payload->>'check_in' as check_in,
  payload->>'check_out' as check_out,
  nullif(payload->>'working_hours', '')::numeric as working_hours,
  coalesce(
    payload->>'final_status',
    payload->>'status',
    payload->>'attendance_status',
    payload->>'mark',
    payload->>'attendance',
    payload->>'present_absent'
  ) as status,
  nullif(payload->>'late_minutes', '')::integer as late_minutes,
  nullif(payload->>'overtime_hours', '')::numeric as overtime_hours,
  payload->>'final_status' as final_status,
  payload->'employee' as employee_details,
  payload as source_payload,
  first_synced_at,
  last_synced_at
from public.attendance_sync_records
where lower(source_table) in ('attendance', 'attendance_data')
   or (lower(source_table) like '%attendance%' and lower(source_table) not like '%leave%');

create view public.attendance_sync_leave
with (security_invoker = true) as
select
  id as sync_id,
  source_project,
  source_table,
  source_record_key,
  payload->>'id' as leave_id,
  payload->>'employee_id' as employee_id,
  coalesce(
    payload->>'employee_name',
    payload->>'full_name',
    payload->>'name',
    payload->>'display_name',
    payload->>'user_name',
    payload->>'staff_name',
    payload->'employee'->>'name',
    payload->'employee'->>'full_name',
    concat_ws(' ', payload->'employee'->>'first_name', payload->'employee'->>'last_name')
  ) as employee_name,
  nullif(coalesce(
    payload->>'start_date',
    payload->>'from_date',
    payload->>'leave_from',
    payload->>'leaveStart',
    payload->>'date',
    payload->>'leave_date'
  ), '')::date as leave_start_date,
  nullif(coalesce(
    payload->>'end_date',
    payload->>'to_date',
    payload->>'leave_to',
    payload->>'leaveEnd',
    payload->>'date',
    payload->>'leave_date'
  ), '')::date as leave_end_date,
  coalesce(
    payload->>'status',
    payload->>'leave_status',
    payload->>'approval_status',
    payload->>'state'
  ) as status,
  payload as source_payload,
  first_synced_at,
  last_synced_at
from public.attendance_sync_records
where lower(source_table) like '%leave%';

-- ---------------------------------------------------------------------------
-- RLS
-- Backend uses service_role, which bypasses RLS. These policies keep direct
-- client access restricted while allowing Admin/Master Admin to inspect data.
-- ---------------------------------------------------------------------------

alter table public.attendance_sync_records enable row level security;
alter table public.attendance_sync_runs enable row level security;

grant select on public.attendance_sync_records to authenticated;
grant select on public.attendance_sync_runs to authenticated;
grant select on public.attendance_sync_attendance to authenticated;
grant select on public.attendance_sync_leave to authenticated;
grant all on public.attendance_sync_records to service_role;
grant all on public.attendance_sync_runs to service_role;
grant select on public.attendance_sync_attendance to service_role;
grant select on public.attendance_sync_leave to service_role;

drop policy if exists attendance_sync_records_admin_select on public.attendance_sync_records;
create policy attendance_sync_records_admin_select
  on public.attendance_sync_records
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.user_profiles up
      join public.roles r on r.id = up.role_id
      where up.id = auth.uid()
        and lower(r.name) in ('admin', 'super_admin', 'superadmin', 'master_admin', 'master_ad', 'masteradmin')
    )
  );

drop policy if exists attendance_sync_records_service_all on public.attendance_sync_records;
create policy attendance_sync_records_service_all
  on public.attendance_sync_records
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists attendance_sync_runs_admin_select on public.attendance_sync_runs;
create policy attendance_sync_runs_admin_select
  on public.attendance_sync_runs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.user_profiles up
      join public.roles r on r.id = up.role_id
      where up.id = auth.uid()
        and lower(r.name) in ('admin', 'super_admin', 'superadmin', 'master_admin', 'master_ad', 'masteradmin')
    )
  );

drop policy if exists attendance_sync_runs_service_all on public.attendance_sync_runs;
create policy attendance_sync_runs_service_all
  on public.attendance_sync_runs
  for all
  to service_role
  using (true)
  with check (true);

notify pgrst, 'reload schema';
